# Default initial positions for giraffe's ros2_control fake system

initial_positions:
  elbow_actuator_elbow_joint: 0
  finger_actuator_gripper_joint: 0
  shoulder_lift_actuator_shoulder_lift_joint: 0
  shoulder_pan_actuator_shoulder_pan_joint: 0
  wrist_1_actuator_wrist_1_joint: 0
  wrist_2_actuator_wrist_2_joint: 0