# MoveIt uses this configuration for controller management
trajectory_execution:
  allowed_execution_duration_scaling: 1.2
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.01
  trajectory_duration_monitoring: true

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_controller
    - gripper_controller

  arm_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - shoulder_pan_actuator_shoulder_pan_joint
      - shoulder_lift_actuator_shoulder_lift_joint
      - elbow_actuator_elbow_joint
      - wrist_1_actuator_wrist_1_joint
      - wrist_2_actuator_wrist_2_joint

  gripper_controller:
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - finger_actuator_gripper_joint
